
name: Build
on: push
jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create config.js
      run: |
          echo $CONFIG_JS >> ./js/config.js
      shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
      env:
        CONFIG_JS : ${{secrets.CONFIG_JS}}
    - name: create build
      run: |
          mkdir build && mv *.html build && mv js css assets -t build
      shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
      env:
        CONFIG_JS : ${{secrets.CONFIG_JS}}
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: build # The folder the action should deploy.
        clean: true # Clean destination before deploy files